#Arquivo.....: docker-compose.yml
# 
#Data........: 03/05/2025
#Autor.......: Datalib Tecnologia e Treinamento em Dados (Saito)
#Copyright...: Utlização somente para fins educacionais e didaticos 
#              com autorização do autor.
#Referencias.: https://www.instaclustr.com/blog/running-apache-cassandra-single-and-multi-node-clusters-on-docker-with-docker-compose/
#Comentario..: 


version: '3.8' 
 
networks: 
  cassandra:
 
services: 
  cassandra10: 
    image: cassandra:latest 
    container_name: cassandra10 
    hostname: cassandra10 
    networks: 
      - cassandra
    ports: 
      - "9042:9042" 

    environment: &environment  
        CASSANDRA_SEEDS: "cassandra10,cassandra20"   
        CASSANDRA_CLUSTER_NAME: MyTestCluster 
        CASSANDRA_DC: DC1 
        CASSANDRA_RACK: RACK1 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
        CASSANDRA_NUM_TOKENS: 128 
  cassandra20: 
    image: cassandra:latest 
    container_name: cassandra20 
    hostname: cassandra20 
    networks: 
      - cassandra
    ports: 
      - "9043:9042" 
    environment: *environment   
    depends_on: 
      cassandra10:  
        condition: service_started 

  cassandra30: 
    image: cassandra:latest 
    container_name: cassandra30 
    hostname: cassandra30 
    networks: 
      - cassandra
    ports: 
      - "9044:9042" 
    environment: *environment   
    depends_on: 
      cassandra20:   
        condition: service_started
